version: '3.7'
services:
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "9001:9001"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      backend:
        aliases:
          - "licenseservice"

#  keycloak:
#    image: jboss/keycloak
#    container_name: "keycloak"
#    restart: always
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#    ports:
#      - "8080:8080"
#    networks:
#      backend:
#        aliases:
#          - "keycloak"

  keycloak:
    image: "quay.io/keycloak/keycloak:19.0"
    container_name: "ejstock-keycloak"
    restart: always
    command: start-dev
#    command: start-dev --import-realm
#    volumes:
#      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "keycloak"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafkaserver:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
    networks:
      backend:
        aliases:
          - "kafka"

  redisserver:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      backend:
        aliases:
          - "redis"

networks:
  backend:
    driver: bridge
