server:
  port: 9000

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9001
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false

management:
  endpoints:
    web:
      #      base-path: /
      exposure:
        include: info, health, refresh, env, gateway
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    gateway:
      access: unrestricted

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5000
    disable-delta: true
    service-url:
      defaultZone: http://localhost:9002/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix: WARN
    org.org.springframework.web: WARN
    kr.ejsoft.lecture: DEBUG