version: '3.7'
services:
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "9001:9001"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      backend:
        aliases:
          - "licenseservice"
networks:
  backend:
    driver: bridge
