server:
  port: 9002

spring:
  application:
    name: config-server
  profiles:
    active:
      - native
#      - git
#      - vault
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
#            - file:///{FILE_PATH}
#        git:
#          uri: https://github.com/parandol/config.git
#          search-paths: licensing-service
#        vault:
#          port: 8200
#          host: 127.0.0.1
#          kv-version: 2
#          backend: licensing-service
#          profile-separator: /

# export ENCRYPT_KEY=.......
encrypt:
  key: secretkey