server:
  port: 9003

spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9001
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false       # true 일 경우 config server에 접속할수 없으면 시작 시 종료. false면 retry 시도 후 내부 기본값 사용

management:
  endpoints:
    web:
#      base-path: /
      exposure:
        include: info, health, refresh, env
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# export ENCRYPT_KEY=.......
encrypt:
  key: secretkey