server:
  port: 9001

spring:
  application:
    name: licensing-service

management:
  endpoints:
    web:
#      base-path: /
      exposure:
        include: info, health, refresh
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
