version: "3.8"
services:
#  catalog-service:
#    depends_on:
#      - polar-postgres
#    image: "chap05-catalog-service"
#    container_name: "chap05-catalog-service"
#    ports:
#      - 9001:9001
#      - 8001:8001
#    environment:
#      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8001
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
#      - SPRING_PROFILES_ACTIVE=testdata

  ejstock-postgres:
    image: "postgres:14.4"
    container_name: "ejstock-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ejstock_dev
